swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints to reach get transaction data
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /account/accounts:
    get:
      security:
        - Bearer: []
      tags:
        - Account
      summary: Get User Accounts
      description: Retrieves the user's accounts
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: Successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/Account'
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
    post:
        security:
            - Bearer: []
        tags:
            - Account
        summary: Create Account
        description: Creates a new account
        parameters:
            - in: header
              name: Authorization
              description: Attach Bearer JWT token
              required: true
              type: string
            - in: body
              name: body
              description: Create Account Request
              required: true
              schema:
                $ref: '#/definitions/CreateAccountRequest'
        produces:
            - application/json
        responses:
            '200':
              description: Successful operation
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    $ref: '#/definitions/CreateAccountResponse'
            '400':
              description: Bad Request
            '401':
              description: Unauthorized
            '500':
              description: Internal Server Error
    patch:
        security:
            - Bearer: []
        tags:
            - Account
        summary: Update Account
        description: Updates the title and description of an account
        parameters:
            - in: header
              name: Authorization
              description: Attach Bearer JWT token
              required: true
              type: string
            - in: body
              name: body
              description: Update Account Request. If either title or description is not provided, the existing value will be used.
              required: true
              schema:
                  type: object
                  properties:
                    account_id:
                      type: string
                    title:
                      type: string
                    description:
                      type: string
        produces:
            - application/json
        responses:
            '200':
              description: Successful operation
              schema:
                  type: object
                  properties:
                    message:
                      type: string
                    data:
                      $ref: '#/definitions/Account'
            '400':
              description: Bad Request
            '401':
              description: Unauthorized
            '500':
              description: Internal Server Error
    delete:
        security:
            - Bearer: []
        tags:
            - Account
        summary: Delete Account
        description: Deletes an account
        parameters:
            - in: header
              name: Authorization
              description: Attach Bearer JWT token
              required: true
              type: string
            - in: query
              name: account_id
              description: Account ID
              required: true
              type: string
        produces:
            - application/json
        responses:
            '200':
              description: Successful operation
              schema:
                  type: object
                  properties:
                    message:
                      type: string
            '400':
              description: Bad Request
            '401':
              description: Unauthorized
            '500':
              description: Internal Server Error
  /categories:
    get:
      summary: Get Categories
      description: Retrieves the list of categories
      tags:
        - Categories
      produces:
        - application/json
      responses:
        '200':
          description: Successful operation
          schema:
            $ref: '#/definitions/Category'
        '500':
          description: Internal Server Error
    post:
        security:
            - Bearer: []
        tags:
            - Categories
        summary: Create Category
        description: Creates a new category
        parameters:
            - in: header
              name: Authorization
              description: Attach Bearer JWT token
              required: true
              type: string
            - in: body
              name: body
              description: Create Category Request
              required: true
              schema:
                  properties:
                    name:
                      type: string
        produces:
            - application/json
        responses:
            '200':
              description: Successful operation
              schema:
                  type: object
                  properties:
                    message:
                      type: string
                    data:
                      $ref: '#/definitions/Category'
            '400':
              description: Bad Request
            '401':
              description: Unauthorized
            '500':
              description: Internal Server Error
  /account/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Get Transactions
      description: Retrieves the list of transactions
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: query
          name: account_id
          description: Account ID
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: Successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/TransactionHistory'
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
    post:
        security:
            - Bearer: []
        tags:
            - User Module
        summary: Create Transaction
        description: Creates a new transaction
        parameters:
            - in: header
              name: Authorization
              description: Attach Bearer JWT token
              required: true
              type: string
            - in: body
              name: body
              description: Create Transaction Request
              required: true
              schema:
                  $ref: '#/definitions/CreateTransactionRequest'
        produces:
            - application/json
        responses:
            '200':
              description: Successful operation
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    $ref: '#/definitions/TransactionHistory'
            '400':
              description: Bad Request
            '401':
              description: Unauthorized
            '500':
              description: Internal Server Error
    patch:
      security:
        - Bearer: [ ]
      tags:
        - User Module
      summary: Update Transaction
      description: Updates the category_id and notes of a transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: body
          name: body
          description: Update Transaction Request. If either category_id or notes is not provided, the existing value will be used.
          required: true
          schema:
            $ref: '#/definitions/UpdateHistoryRequest'
      produces:
        - application/json
      responses:
        '200':
          description: Successful operation
          schema:
            type: object
            properties:
              message:
                type: string
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
definitions:
  CreateAccountRequest:
    type: object
    properties:
      title:
        type: string
      description:
        type: string
      currency:
        type: string
  CreateAccountResponse:
    type: object
    properties:
      message:
        type: string
      title:
        type: string
      description:
        type: string
      currency:
        type: string
      id:
        type: string
      balance:
        type: number
      number_of_transactions:
        type: integer
  UpdateHistoryRequest:
    type: object
    properties:
      history_id:
        type: string
      category_id:
        type: string
      notes:
        type: string
  Account:
    type: object
    properties:
      title:
        type: string
      number_of_transactions:
        type: integer
      balance:
        type: number
      currency:
        type: string
      description:
        type: string
      id:
        type: string
  Category:
    type: object
    properties:
      objectID:
        type: string
  TransactionHistory:
    type: object
    properties:
      date:
        type: string
        format: date
      description:
        type: string
      amount:
        type: number
      currency:
        type: string
      type:
        type: string
      balance:
        type: number
      notes:
        type: string
      category_id:
        type: string
      transactionType:
        type: string
  CreateTransactionRequest:
    type: object
    properties:
      account_id:
        type: string
      amount:
        type: number
      currency:
        type: string
      type:
        type: string
      description:
        type: string
      notes:
        type: string
      category_id:
        type: string